version: 2
jobs:
  docs-build-test:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/docs
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
        name: test our generated HTML files
        command: |
          htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
          --empty-alt-ignore --disable-external
          
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: $HUGO_BUILD_DIR
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "bill.morrison@teamsolutionz.com"
            git config user.name "Bill Morrison"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist $HUGO_BUILD_DIR
          
workflows:
  version: 2
  build:
    jobs:
      - docs-build-test
      - docs-deploy:
          requires:
            - docs-build-test
